### ISSUE TITLE
Problemas con el enlace en una sugerencia.

### ISSUE THREAD

**Issue by jeiver** [pureexe/FossilGraderTuToi9#1]
En la sugerencia " ...puedes encontrar un archivo de ayuda de Dev-C++ en Español?<CR><CR>Para descargarte un instalador con ayuda en Español ve a la dirección indicada después.<CR><CR>Elije el archivo help-installer.exe en<CR><URL>http://membres.lycos.fr/ledesma/help/<UDESC> "
el enlace está caído. ¿Usted sabe donde puedo encontrar la informacion que se ofrecia allí?

**Comment by pureexe** [comment]
Sorry I can't read Spanish.
And this repository isn't my project. Just a fork from [tutoi9.com](http://tutoi9.com)
For now, Tutoi9.com site is permanently closed.
Maybe you can contact their from [Facebook page](https://www.facebook.com/tu.toi.9th/).
